language: ruby

services:
  - docker

script: 
  - bash ./scripts/runTests.sh
  - bash ./scripts/createProd.sh

deploy:
  provider: script
  script: bash ./scripts/pushImage.sh
  on: 
    branch: feature/travisSupport
