language: ruby

services:
  - docker

script: 
  - bash ./scripts/runTests.sh
  - bash ./scripts/pushImage.sh

# deploy:
#   provider: script
#   script: bash ./pushImage.sh
#   on: 
#     branch: master
