# base image
FROM node:alpine

# set working directory
WORKDIR /referee-coordinator

# add `/referee-coordinator/node_modules/.bin` to $PATH
ENV PATH /referee-coordinator/node_modules/.bin:$PATH

# install and cache referee-coordinator dependencies
COPY package.json /referee-coordinator/package.json
RUN npm install
RUN npm install react-scripts@3.0.1 -g
COPY . .
RUN npm run build
# test referee-coordinator
